HR.Project.Own.UI/Models/ErrorViewModel.cs
namespace HR.Project.Own.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HR.Project.Own.UI/Controllers/AdvanceController.cs
using HR.Project.Own.EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace HR.Project.Own.UI.Controllers
{
    public class AdvanceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AvansTalepEt()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AvansTalepEt(Advance advance)
        {
            return View(advance);
        }

        public IActionResult AvansListele()
        {
            return View();
        }
    }
}

HR.Project.Own.UI/Controllers/ErrorPageController.cs
using Microsoft.AspNetCore.Mvc;

namespace HR.Project.Own.UI.Controllers
{
    public class ErrorPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HR.Project.Own.UI/Controllers/HomeController.cs
using HR.Project.Own.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HR.Project.Own.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HR.Project.Own.UI/Controllers/LoginController.cs
using HR.Project.Own.EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace HR.Project.Own.UI.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            return View();
        }
        
        public IActionResult Login()
        {
            return View();
        }


    }
}

HR.Project.Own.UI/Controllers/PermissionController.cs
using Microsoft.AspNetCore.Mvc;

namespace HR.Project.Own.UI.Controllers
{
    public class PermissionController : Controller
    {
        public IActionResult PermissionRequest()
        {
            return View();
        }
        
        public IActionResult PermissionList()
        {
            return View();
        }
    }
}

HR.Project.Own.UI/Controllers/PersonalController.cs
using HR.Project.Own.EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace HR.Project.Own.UI.Controllers
{
    public class PersonalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Bilgilerim()
        {
            return View();
        }

        [HttpGet]
        public IActionResult BilgilerimiGuncelle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BilgilerimiGuncelle(User user)
        {
            return View();
        }
    }
}

HR.Project.Own.UI/Controllers/SpendingController.cs
using HR.Project.Own.EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace HR.Project.Own.UI.Controllers
{
    public class SpendingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SpendingRequest()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SpendingRequest(Spending spending)
        {
            return View();
        }
        
        public IActionResult SpendingList()
        {
            return View();
        }

        
    }
}

HR.Project.Own.UI/Views/Login/Register.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/writer/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/writer/assets/vendors/css/vendor.bundle.base.css">
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/writer/assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/writer/assets/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper full-page-wrapper">
            <div class="content-wrapper d-flex align-items-center ">
                <div class="row flex-grow">
                    <div class="col-lg-8 mx-auto">
                        <div class="auth-form-light text-left p-5">
                            <div class="brand-logo">
                                <img src="~/writer/assets/images/LogoGIS.png">
                            </div>
                            <form class="pt-3">
                                <div class="col-12 font-weight-bold">
                                    <div style="background-color:honeydew" class="card">
                                        <div class="card-body">
                                            <h2 class="card-title text-center">KAYIT</h2>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Adı *</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">2. Adı</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Soyadı *</label>
                                                        <div class="col-sm-9">
                                                            <input type="text" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Telefon *</label>
                                                        <div class="col-sm-9">
                                                            <input type="number" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Mail Adresi *</label>
                                                        <div class="col-sm-9">
                                                            <input type="email" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Doğum Tarihi *</label>
                                                        <div class="col-sm-9">
                                                            <input class="form-control" type="date" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">TC No *</label>
                                                        <div class="col-sm-9">
                                                            <input type="number" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Cinsiyet</label>
                                                        <div class="col-sm-9">
                                                            <select class="form-control">
                                                                <option>Erkek</option>
                                                                <option>Kadın</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>                                            
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Adresi</label>
                                                        <div class="col-sm-12">
                                                            <textarea style="margin-bottom:20px" id="adres1" name="#" rows="4" class="form-control"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Şifre *</label>
                                                        <div class="col-sm-9">
                                                            <input type="password" class="form-control" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group row">
                                                        <label class="col-sm-3 col-form-label">Şifre Tekrar *</label>
                                                        <div class="col-sm-9">
                                                            <input class="form-control" type="password" />
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>                                            
                                            <button asp-controller="Login" asp-action="Login" type="submit" class="btn btn-gradient-info btn-block">Kaydet</button>
                                            <br />
                                        </div>
                                    </div>
                                </div>

                                @*
                                <div class="form-group">
                                <input type="password" class="form-control form-control-lg" id="exampleInputPassword1" placeholder="Password">
                                </div>
                                <div class="mb-4">
                                <div class="form-check">
                                <label class="form-check-label text-muted">
                                <input type="checkbox" class="form-check-input"> I agree to all Terms & Conditions
                                </label>
                                </div>
                                </div>
                                <div class="mt-3">
                                <a class="btn btn-block btn-gradient-primary btn-lg font-weight-medium auth-form-btn" href="~/writer/index.html">KAYIT OL</a>
                                </div>
                                <div class="text-center mt-4 font-weight-light">
                                Already have an account? <a href="~/writer/login.html" class="text-primary">Login</a>
                                </div>*@
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/writer/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/writer/assets/js/off-canvas.js"></script>
    <script src="~/writer/assets/js/hoverable-collapse.js"></script>
    <script src="~/writer/assets/js/misc.js"></script>
    <!-- endinject -->
</body>
</html>

HR.Project.Own.UI/Views/Permission/PermissionRequest.cshtml
@using HR.Project.Own.EntityLayer.Concrete
@model Permission

@{
    ViewData["Title"] = "Permission Request";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <form asp-controller="Permission" asp-action="PermissionRequest" method="post" novalidate="novalidate"> 
        <div class="col-9 mx-auto">
            <div style="background-color:honeydew" class="card">
                <div class="card-body">
                    <h2 class="card-title">İZİN TALEP ET</h2>
                    <br />
                    <div class="row">
                        <div class="form-group row">
                            <label asp-for="PermissionType" class="col-sm-3 col-form-label">İzin Türü</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Harcama Miktarı</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Para Birimi</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Açıklama</label>
                            <div class="col-sm-9">
                                <textarea style="margin-bottom:20px" id="aciklama" name="#" rows="4" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                    <button style="margin-bottom:60px" type="submit" class="btn btn-gradient-info btn-block">Kaydet</button>
                    <br />
                </div>
            </div>
        </div>
    </form>

    <script src="~/writer/assets/vendors/js/vendor.bundle.base.js"></script>   
    <script src="~/writer/assets/js/off-canvas.js"></script>
    <script src="~/writer/assets/js/hoverable-collapse.js"></script>
    <script src="~/writer/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/writer/assets/js/file-upload.js"></script>
    <!-- End custom js for this page -->
</body>

HR.Project.Own.UI/Views/Personal/BilgilerimiGuncelle.cshtml
@using HR.Project.Own.EntityLayer.Concrete
@using HR.Project.Own.EntityLayer.Enum
@model User

@{
    ViewData["Title"] = "Bilgilerimi Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <form asp-controller="Personal" asp-action="BilgilerimiGuncelle" method="post" novalidate="novalidate">
        <div class="col-12">
            <div style="background-color:honeydew" class="card">
                <div class="card-body">
                    <h3 class="card-title">BİLGİLERİMİ GÜNCELLE</h3>
                    <br />
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="Adi" class="col-sm-3 col-form-label">Adı</label>
                                <div class="col-sm-9">
                                    <input asp-for="Adi" type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="Adi2" class="col-sm-3 col-form-label">2. Adı</label>
                                <div class="col-sm-9">
                                    <input asp-for="Adi2" type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="Soyadi" class="col-sm-3 col-form-label">Soyadı</label>
                                <div class="col-sm-9">
                                    <input asp-for="Soyadi" type="text" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="CepTelefonu" class="col-sm-3 col-form-label">Telefonu</label>
                                <div class="col-sm-9">
                                    <input asp-for="CepTelefonu" type="number" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="Email" class="col-sm-3 col-form-label">Mail Adresi</label>
                                <div class="col-sm-9">
                                    <input asp-for="Email" type="email" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="DogumTarihi" class="col-sm-3 col-form-label">Doğum Tarihi</label>
                                <div class="col-sm-9">
                                    <input asp-for="DogumTarihi" class="form-control" type="date" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="TCNo" class="col-sm-3 col-form-label">TC No</label>
                                <div class="col-sm-9">
                                    <input asp-for="TCNo" type="number" class="form-control" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="Gender" class="col-sm-3 col-form-label">Cinsiyeti</label>
                                <div class="col-sm-9">
                                    <select asp-for="Gender" class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Gender))">
                                        <option>Cinsiyetiniz</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="IseGirisTarihi" class="col-sm-3 col-form-label">İşe Giriş Tarihi</label>
                                <div class="col-sm-9">
                                    <input asp-for="IseGirisTarihi" class="form-control" type="date" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label asp-for="IstenCikisTarihi" class="col-sm-3 col-form-label">İşten Çıkış Tarihi</label>
                                <div class="col-sm-9">
                                    <input asp-for="IstenCikisTarihi" class="form-control" type="date" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group row">
                                <label asp-for="Adres" class="col-sm-3 col-form-label">Adresi</label>
                                <div class="col-sm-12">
                                    <textarea asp-for="Adres" style="margin-bottom:20px" id="adres1" name="#" rows="4" class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button style="margin-bottom:60px" type="submit" class="btn btn-gradient-info btn-block">Kaydet</button>
                    <br />
                </div>
            </div>
        </div>

    </form>


    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="../../assets/js/file-upload.js"></script>
    <!-- End custom js for this page -->
</body>

HR.Project.Own.UI/Views/Spending/SpendingRequest.cshtml
@using HR.Project.Own.EntityLayer.Concrete
@using HR.Project.Own.EntityLayer.Enum
@model Spending

@{
    ViewData["Title"] = "Harcama Talep Et";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <form asp-controller="Spending" asp-action="SpendingRequest" method="post" novalidate="novalidate">
        <div class="col-9 mx-auto">
            <div style="background-color:honeydew" class="card">
                <div class="card-body">
                    <h2 class="card-title">HARCAMA TALEP ET</h2>
                    <br />
                    <div class="row">
                        <div class="form-group row">
                            <label asp-for="SpendingType" class="col-sm-3 col-form-label">Harcama Türü</label>
                            <div class="col-sm-9">
                                <select asp-for="SpendingType" class="form-control" asp-items="@Html.GetEnumSelectList(typeof(SpendingType))">
                                    <option>Lütfen Bir Harcama Türü Seçiniz...</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group row">
                            <label class="col-sm-3 col-form-label">Harcama Miktarı</label>
                            <div class="col-sm-9">
                                <input asp-for="SpendingAmount" type="number" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group row">
                            <label asp-for="Currency" class="col-sm-3 col-form-label">Para Birimi</label>
                            <div class="col-sm-9">
                                <select asp-for="Currency" class="form-control" asp-items="@Html.GetEnumSelectList(typeof(Currency))">
                                    <option>Lütfen Bir Para Birimi Seçiniz...</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group row">
                            <label asp-for="Description" class="col-sm-3 col-form-label">Açıklama</label>
                            <div class="col-sm-9">
                                <textarea asp-for="Description" style="margin-bottom:20px" id="aciklama" name="#" rows="4" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                    <button style="margin-bottom:60px" type="submit" class="btn btn-gradient-info btn-block">Kaydet</button>
                    <br />
                </div>
            </div>
        </div>
    </form>

    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/writer/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/writer/assets/js/off-canvas.js"></script>
    <script src="~/writer/assets/js/hoverable-collapse.js"></script>
    <script src="~/writer/assets/js/misc.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/writer/assets/js/file-upload.js"></script>
    <!-- End custom js for this page -->
</body>